apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: translator
type: Opaque
stringData:
  POSTGRES_USER: translator
  POSTGRES_PASSWORD: translator-secret
  POSTGRES_DB: translator
